@api = http://localhost:8080/api
@_json = Content-Type: application/json
GET {{api}}/songs
###
POST {{api}}/albums


{
    "id": "4",
    "title": "L.O.V.E",
    "artist": "Devin Morrison",
    "price": 20.99
}
###
GET {{api}}/content
###
POST {{api}}/content
{{_json}}

{
    "providerId": 1,
    "content": "Um teste de quanto ele aguenta de request",
    "isBinary": false
}